[dependencies]
base = "0.8.1"
itertools = "0.1.1"
circular-buffer = "0.0.1"
bitbuffer = "1.1.2"
hash = "https://github.com/tomijaga/hash.mo#master"
buffer-deque = "0.0.1"
array = "https://github.com/aviate-labs/array.mo#v0.2.1"